// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DalEstudiantes.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DalEstudiantes.Models
{
    public partial interface IEstudiantesContextProcedures
    {
        Task<List<SpIniciarSesionResult>> SpIniciarSesionAsync(string identificacion, string contrasena, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpRegistrarEstudianteResult>> SpRegistrarEstudianteAsync(string identificacion, string nombreCompleto, string contrasena, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
