// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DalEstudiantes.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DalEstudiantes.Models
{
    public partial interface IEstudiantesContextProcedures
    {
        Task<int> SpDeleteEstudianteAsync(int? idEstudiante, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpGetEstudianteResult>> SpGetEstudianteAsync(int? idEstudiante, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpGetEstudianteXMateriasResult>> SpGetEstudianteXMateriasAsync(int? idEstudiante, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpIniciarSesionResult>> SpIniciarSesionAsync(string identificacion, string contrasena, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpRegistrarEstudianteResult>> SpRegistrarEstudianteAsync(string identificacion, string nombreCompleto, string contrasena, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SpUpdateEstudianteAsync(int? idEstudiante, string identificacion, string nombreEstudiante, string contrasena, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
