// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DalEstudiantes.Models
{
    public partial class SpAsignarMateriasResult
    {
        [StringLength(200)]
        public string Mensaje { get; set; }
        public bool? Asingado { get; set; }
    }
}
