// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DalEstudiantes.Models
{
    public partial class SpGetEstudianteXMateriasResult
    {
        [StringLength(15)]
        public string Identificacion { get; set; }
        [StringLength(50)]
        public string NombreEstudiante { get; set; }
    }
}
